@startuml
'https://plantuml.com/class-diagram

class Main {
-Console console
-PrintManager printManager
+{static}void main(String[])
+void run(String[])
+void menu()
-void initialize()
+String stringInput()
+int menuChoice(int)
+int numberInput()
+int numberInput(int, int)
}

class Console {
-String printStrategy
+void showPrints()
+void showSpools()
+void showPrinters()
+void showPendingPrintTasks()
}

class Reader {
-Scanner scanner
+ArrayList<Print> readPrintsFromFile(String)
+ArrayList<Printers> readPrintersFromFile(String)
+ArrayList<Spools> readSpoolsFromFile(String)
}

class TaskManager {
+void addNewPrintTask()
+void StartPrintQueue()
+void changePrintStrategy()
+void registerPrinterCompletion()
+void registerPrinterFailure()
}

Main *.. Console
Main::menuChoice *.. TaskManager
Main::initialize *.. Reader

@enduml